# List of the vs code extensions
vscode:
  extensions:
    - ms-python.python
    - ms-azuretools.vscode-docker

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8501
    onOpen: open-preview

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo "Ready to go"
    command: echo "Lets go"

  - init: pip install -r requirements.txt
    command: streamlit run example_app.py
    openMode: split-right